// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// emp_mode
Rcpp::List emp_mode(std::vector<double> data, Rcpp::Nullable<double> fix_lower, Rcpp::Nullable<double> fix_upper, bool smooth, Rcpp::String smooth_option, bool smooth_density, int density_points, Rcpp::Nullable<int> m_degree, int sample_size, Rcpp::Nullable<int> m_knots);
RcppExport SEXP _modeFinder_emp_mode(SEXP dataSEXP, SEXP fix_lowerSEXP, SEXP fix_upperSEXP, SEXP smoothSEXP, SEXP smooth_optionSEXP, SEXP smooth_densitySEXP, SEXP density_pointsSEXP, SEXP m_degreeSEXP, SEXP sample_sizeSEXP, SEXP m_knotsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::vector<double> >::type data(dataSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<double> >::type fix_lower(fix_lowerSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<double> >::type fix_upper(fix_upperSEXP);
    Rcpp::traits::input_parameter< bool >::type smooth(smoothSEXP);
    Rcpp::traits::input_parameter< Rcpp::String >::type smooth_option(smooth_optionSEXP);
    Rcpp::traits::input_parameter< bool >::type smooth_density(smooth_densitySEXP);
    Rcpp::traits::input_parameter< int >::type density_points(density_pointsSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<int> >::type m_degree(m_degreeSEXP);
    Rcpp::traits::input_parameter< int >::type sample_size(sample_sizeSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<int> >::type m_knots(m_knotsSEXP);
    rcpp_result_gen = Rcpp::wrap(emp_mode(data, fix_lower, fix_upper, smooth, smooth_option, smooth_density, density_points, m_degree, sample_size, m_knots));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_modeFinder_emp_mode", (DL_FUNC) &_modeFinder_emp_mode, 10},
    {NULL, NULL, 0}
};

RcppExport void R_init_modeFinder(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
