# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Compute the univariate empirical mode via Bernstein polynomials.
#' 
#' 
#'  
#' 
#' @param data A univariate sample data.
#' @param threshold A number of subsample size used in Anderson-Darling tests, and default is 100L.
#' @param smooth A indicator of if performing Bernstein polynomials smoothing or not; If TRUE (default), adapt Bernstein polynomials smoothing.
#' @param smooth_option A name of method of finding maximum based on the Bernstein polynomials density, and "optimalOfPdf" (default) indicates finding optimum on the smoothing density.
#' @param fix_lower A value of the lower bound of the the sample data; If NULL (default), set min{0, the minimum of the sample data}; Set a particualr value otherwise.
#' @param fix_upper A value of the upper bound of the the sample data; If NULL (default), set max{1, the maximum of the sample data}; Set a particualr value otherwise.
#' @param m_degree A number of degree of Bernstein polynomials; If NA (default), set the one with maximal p-value that less than 0.95; Set a particualr value otherwise.
#' @param m_knots A number of knots in finding the maximum of Bernstein polynomials density; If NA (default), set n / log(n); Set a particualr value otherwise.
#' @return The empirical mode of \code{data}, the degree of Bernstein polynomials used and the corresponding p-value of the Anderson-Darling test based on the subsample and Bernstein polynomials.
#' @examples
#' m_threshold = 1e3
#' n = 1e6
#' set.seed(1)
#' data = rbeta(n, 2, 5)
#' emp_mode(data, threshold = m_threshold)
#' @export
emp_mode <- function(data, threshold = NULL, smooth = TRUE, smooth_option = "optimalOfPdf", fix_lower = NULL, fix_upper = NULL, m_degree = NULL, m_knots = NULL) {
    .Call('_modeFinder_emp_mode', PACKAGE = 'modeFinder', data, threshold, smooth, smooth_option, fix_lower, fix_upper, m_degree, m_knots)
}

